In [18]:
import pandas as pd
from scipy.stats import pearsonr, spearmanr
from statsmodels.stats.multitest import multipletests

import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import date
import numpy as np
import datetime

pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

In [19]:
df1 = pd.read_csv("data/H3K9me3_gene_logFC_corr.csv")
df1.head()

,gene,n_points,pearson_r,pearson_p,spearman_r,spearman_p,pearson_fdr,spearman_fdr
0,H2-K1,91,-0.640831,7.830740e-12,-0.564398,5.658477e-09,2.063870e-07,0.000149
1,Ppm1e,91,-0.564186,5.749935e-09,-0.506889,2.943824e-07,7.577265e-05,0.001940
2,Patl2,91,-0.553086,1.306696e-08,-0.418614,3.636562e-05,1.147976e-04,0.018579
3,Odf3b,91,-0.547649,1.932426e-08,-0.230315,2.807010e-02,1.273276e-04,0.398633
4,Oas1b,91,-0.543045,2.677080e-08,-0.268580,1.004858e-02,1.411142e-04,0.250972

In [20]:
df2 = pd.read_csv("data/H3K9me3_geneTPM_corr.csv")
df2.head()

,gene,n_points,pearson_r,pearson_p,spearman_r,spearman_p,pearson_fdr,spearman_fdr
0,0610005C13Rik,91,-0.021298,0.841178,0.003536,0.973466,NaN,NaN
1,0610006L08Rik,91,-0.046330,0.662776,0.039773,0.708171,NaN,NaN
2,0610009B22Rik,91,0.067036,0.527807,0.050264,0.636103,NaN,NaN
3,0610009E02Rik,91,-0.212521,0.043129,-0.335579,0.001147,NaN,NaN
4,0610009L18Rik,91,-0.035892,0.735539,-0.162134,0.124671,NaN,NaN

In [21]:
df = pd.merge(df1, df2, how="outer", on="gene", suffixes=('_logFC', '_TPM')).sort_values("spearman_fdr_logFC")
df.head()

,gene,n_points_logFC,pearson_r_logFC,pearson_p_logFC,spearman_r_logFC,spearman_p_logFC,pearson_fdr_logFC,spearman_fdr_logFC,n_points_TPM,pearson_r_TPM,pearson_p_TPM,spearman_r_TPM,spearman_p_TPM,pearson_fdr_TPM,spearman_fdr_TPM
18405,H2-K1,91.0,-0.640831,7.830740e-12,-0.564398,5.658477e-09,2.063870e-07,0.000149,91.0,-0.000437,9.967167e-01,-0.287148,5.785077e-03,NaN,NaN
7244,Exoc7,91.0,0.276696,7.929089e-03,0.527017,8.021263e-08,2.702521e-01,0.001057,91.0,0.026612,8.022805e-01,0.067495,5.249821e-01,NaN,NaN
27482,Snx33,91.0,0.398967,8.956624e-05,0.509811,2.449964e-07,2.052702e-02,0.001940,91.0,-0.524537,9.458025e-08,-0.582402,1.397272e-09,NaN,NaN
24505,Ppm1e,91.0,-0.564186,5.749935e-09,-0.506889,2.943824e-07,7.577265e-05,0.001940,91.0,0.411131,5.160219e-05,0.333413,1.239962e-03,NaN,NaN
18217,Grik2,91.0,-0.433292,1.786334e-05,-0.498836,4.839895e-07,6.631073e-03,0.002551,91.0,0.176839,9.356933e-02,0.260981,1.246678e-02,NaN,NaN

In [22]:
df = df[['gene', 'n_points_logFC', 'spearman_r_logFC', 'spearman_p_logFC', 'spearman_fdr_logFC', 'n_points_TPM', 'spearman_r_TPM', 'spearman_p_TPM', 'spearman_fdr_TPM']]
df = df.rename(columns={
    'n_points_logFC': 'n_cell_types_logFC',
    'n_points_TPM': 'n_cell_types_TPM'
})

In [23]:
df.to_csv("data/H3K9me3_gene-logFC-TPM_include-low-express-gene_corr.csv", index=False)